name: Deploy

on:
  push:
    branches:
      - docs-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: docs/.vitepress/dist
          # cname: example.com # if wanna deploy to custom domain
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: peiyanlu/git-branch-sync-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
#          SSH_KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        with:
          source-repo: "git@github.com:peiyanlu/vite-press.git"
          destination-repo: "git@gitee.com:peiyanlu/vite-press-test.git"


  gitee-pages-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: peiyanlu
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: peiyanlu/vite-press
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
